pom.xml

There are pull requests which Travis jobs are failing due to clirr check goal failures.
We have renamed methods `getFilename` to `getFileName`, which breaks backward compatibility. That's, however, acceptable given we are working on an 1.0-alpha release series.
So I suggest we disable in Travis-CI Clirr checks for now, by simply removing `clirr:check` from the Maven default goal in the project `pom.xml`.
Cheers
Bruno

Disable clirr report for now (alpha releases)

---

src/changes/changes.xml
src/main/java/org/apache/commons/imaging/formats/tiff/photometricinterpreters/PhotometricInterpreter.java
src/main/java/org/apache/commons/imaging/formats/tiff/photometricinterpreters/PhotometricInterpreterLogLuv.java
src/test/java/org/apache/commons/imaging/formats/tiff/photometricinterpreters/PhotometricInterpreterLogLuvTest.java

Noticed that the `PhotometricInterpretaterLogLuv` had no coverage, so decided to write some simple unit tests.
Then found a `cube` method that can be replaced by `Math.pow(N, 3)`, and also that there is no javadocs about what is XYZ, why LAB, what is CIE, or even what is Photometric Interpretation.

[IMAGING-228] Drop cube method and add unit tests for PhotometricInterpretationLogLuv

---

src/changes/changes.xml
src/main/java/org/apache/commons/imaging/common/itu_t4/T4AndT6Compression.java

Just wrapped the code around a try in one method, and in the other one created two resources instead of one (properly closed) that received another (not properly closed) as constructor argument.

IMAGING-230: Properly close resources with try-with-resources

---

src/main/java/org/apache/commons/imaging/ImageParser.java
src/main/java/org/apache/commons/imaging/Imaging.java
src/main/java/org/apache/commons/imaging/formats/tiff/TiffImageParser.java

In my other PR #51 there was one failure in Travis due to Javadoc and headings out of order.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.0:javadoc (default-cli) on project commons-imaging: An error has occurred in Javadoc report generation: 
[ERROR] Exit code: 1 - /home/travis/build/apache/commons-imaging/src/main/java/org/apache/commons/imaging/Imaging.java:48: error: heading used out of sequence: <H3>, compared to implicit preceding heading: <H1>
[ERROR]  * <h3>Application Notes</h3>
[ERROR]    ^
[ERROR] /home/travis/build/apache/commons-imaging/src/main/java/org/apache/commons/imaging/ImageParser.java:63: error: heading used out of sequence: <H3>, compared to implicit preceding heading: <H1>
[ERROR]  * <h3>Application Notes</h3>
[ERROR]    ^ …
```

Fix javadoc for Java 13 (heading out of order)

---

src/main/java/org/apache/commons/imaging/formats/gif/GifImageData.java
src/main/java/org/apache/commons/imaging/formats/gif/GifImageMetadata.java
src/main/java/org/apache/commons/imaging/formats/gif/GifImageMetadataItem.java
src/main/java/org/apache/commons/imaging/formats/gif/GifImageParser.java
src/test/java/org/apache/commons/imaging/formats/gif/GifReadTest.java

This PR adds support to read more than one image from a GIF file. It also allows reading of metadata needed for visualization (such as the offset for each image). I did not yet create a jira account but will do so for any future pull requests. I quickly dug into code as I got frustrated with an old [bug](https://stackoverflow.com/questions/22259714/arrayindexoutofboundsexception-4096-while-reading-gif-file) in ImageIO. I hope you'll accept my PR or let me know what to change to meet the code standard.

[IMAGING-236] Add support to read multiple images from GIF

---

src/changes/changes.xml
src/main/java/org/apache/commons/imaging/formats/png/chunks/PngChunk.java
src/main/java/org/apache/commons/imaging/formats/png/chunks/PngChunkIccp.java
src/main/java/org/apache/commons/imaging/formats/png/chunks/PngChunkPlte.java
src/test/java/org/apache/commons/imaging/formats/png/chunks/PngChunkIccpTest.java

Returns copied byte arrays, adds javadocs, and also adds a unit test for the ICCP chunk.

IMAGING-238: Return copied byte arrays in PNG Chunk and ICCP PNG Chunk

---

pom.xml
src/test/java/org/apache/commons/imaging/TestImageReadException.java
src/test/java/org/apache/commons/imaging/TestImageWriteException.java
src/test/java/org/apache/commons/imaging/roundtrip/BitmapRoundtripTest.java
src/test/java/org/apache/commons/imaging/roundtrip/FullColorRoundtrip.java
src/test/java/org/apache/commons/imaging/roundtrip/GrayscaleRountripTest.java
src/test/java/org/apache/commons/imaging/roundtrip/LimitedColorRoundtripTest.java
src/test/java/org/apache/commons/imaging/roundtrip/PixelDensityRoundtrip.java
src/test/java/org/apache/commons/imaging/roundtrip/RoundtripBase.java

This PR follows up https://github.com/apache/commons-imaging/pull/59 and completes the migration to JUnit Jupiter:
- Usages of `org.junit.Assert.assert[Not]Null` were replaced with `org.junit.jupiter.api.Assertions.asserrt[Not]Null`.
- Usages of `@Theories` and `@DataPoints` where replaces with JUnit Jupiter's `@ParameterizedTest` with `@MethodSources`. Unfortunately, Jupiter doesn't have a built-in capability to create a Cartesian product of datapoints like `@Theories` does, so this logic had to be explicitly implemented in `RountripBase`.
- With this cleanup, the additional Junit 5 Vintage dependencies could be removed.

IMAGING-242 Complete the migration to JUnit Jupiter

---

src/test/java/org/apache/commons/imaging/ImagingTest.java
src/test/java/org/apache/commons/imaging/common/bytesource/ByteSourceTest.java
src/test/java/org/apache/commons/imaging/formats/bmp/BmpRoundtripTest.java
src/test/java/org/apache/commons/imaging/formats/icns/IcnsRoundTripTest.java
src/test/java/org/apache/commons/imaging/formats/ico/IcoRoundtripTest.java
src/test/java/org/apache/commons/imaging/formats/jpeg/exif/ExifRewriteTest.java
src/test/java/org/apache/commons/imaging/formats/jpeg/exif/WriteExifMetadataExampleTest.java
src/test/java/org/apache/commons/imaging/formats/jpeg/iptc/IptcAddTest.java
src/test/java/org/apache/commons/imaging/formats/jpeg/iptc/IptcUpdateTest.java
src/test/java/org/apache/commons/imaging/formats/jpeg/xmp/JpegXmpRewriteTest.java
src/test/java/org/apache/commons/imaging/formats/png/ConvertPngToGifTest.java
src/test/java/org/apache/commons/imaging/formats/png/PngMultipleRoundtripTest.java
src/test/java/org/apache/commons/imaging/formats/png/PngTextTest.java
src/test/java/org/apache/commons/imaging/formats/png/PngWriteForceTrueColorText.java
src/test/java/org/apache/commons/imaging/formats/png/PngWriteReadTest.java
src/test/java/org/apache/commons/imaging/formats/tiff/TiffRoundtripTest.java
src/test/java/org/apache/commons/imaging/formats/xmp/XmpUpdateTest.java
src/test/java/org/apache/commons/imaging/roundtrip/NullParametersRoundtripTest.java
src/test/java/org/apache/commons/imaging/roundtrip/PixelDensityRoundtrip.java
src/test/java/org/apache/commons/imaging/roundtrip/RoundtripBase.java

As per title, the `ImagingTest` base class has most of the logic that is handling to traverse directories and load files, which is part of the problem described in IMAGING-155.
This PR does not close IMAGING-155, but starts by removing the method `createTempFile` that also uses an instance `File` annotated by Junit's `TempDir` as base directory - turns out this directory is not really necessary as we only use the `File` created per method.
There was also a similar method in `RoundTripBase` that was also removed in favor of the JDK's method.
Further pull requests will keep tidying `ImagingTest`.
Bruno

[IMAGING-155]: cleaning up ImagingTest base class by removing createTempFile method and using the JDK File method instead

---

src/changes/changes.xml
src/main/java/org/apache/commons/imaging/ImageParser.java
src/main/java/org/apache/commons/imaging/Imaging.java
src/main/java/org/apache/commons/imaging/common/XmpEmbeddable.java
src/main/java/org/apache/commons/imaging/formats/bmp/BmpImageParser.java
src/main/java/org/apache/commons/imaging/formats/dcx/DcxImageParser.java
src/main/java/org/apache/commons/imaging/formats/gif/GifImageParser.java
src/main/java/org/apache/commons/imaging/formats/icns/IcnsImageParser.java
src/main/java/org/apache/commons/imaging/formats/ico/IcoImageParser.java
src/main/java/org/apache/commons/imaging/formats/jpeg/JpegImageParser.java
src/main/java/org/apache/commons/imaging/formats/pcx/PcxImageParser.java
src/main/java/org/apache/commons/imaging/formats/png/PngImageParser.java
src/main/java/org/apache/commons/imaging/formats/pnm/PnmImageParser.java
src/main/java/org/apache/commons/imaging/formats/psd/PsdImageParser.java
src/main/java/org/apache/commons/imaging/formats/rgbe/RgbeImageParser.java
src/main/java/org/apache/commons/imaging/formats/tiff/TiffImageParser.java
src/main/java/org/apache/commons/imaging/formats/wbmp/WbmpImageParser.java
src/main/java/org/apache/commons/imaging/formats/xbm/XbmImageParser.java
src/main/java/org/apache/commons/imaging/formats/xpm/XpmImageParser.java

An alternative propose to IMAGING-163. See #9 for another approach.
In this PR, a new interface `XmpEmbeddable` is added. The `getXmpXml` method is removed from the `ImageParser`, and from any parser that was always returning `null`.
Now, instead, only the parsers that currently support XMP metadata tags implement that method. Not all parsers will implement this interface, as not all image format specifications support XMP.

[IMAGING-163] Add XmpEmbedabble interface to parsers that support it

---

src/changes/changes.xml
src/main/java/org/apache/commons/imaging/palette/ColorComponent.java
src/main/java/org/apache/commons/imaging/palette/ColorCountComparator.java
src/main/java/org/apache/commons/imaging/palette/ColorGroup.java
src/main/java/org/apache/commons/imaging/palette/LongestAxisMedianCut.java
src/main/java/org/apache/commons/imaging/palette/MedianCutQuantizer.java
src/main/java/org/apache/commons/imaging/palette/MostPopulatedBoxesMedianCut.java

This PR creates a `Comparator` for `ColorCount`, replacing two comparators created in different parts of the code with the same logic.
The list that was sorted was a member of a class that could be used elsewhere. So instead of altering the values in that list, now other classes need to access that list through a method that returns a copy of the list.
Members in the package-protected class were made package-protected (from public) or private.
Bruno

IMAGING-151: use a copy of the list, make members package-protected/private, and re-use Comparator

---

src/changes/changes.xml
src/main/java/org/apache/commons/imaging/formats/jpeg/iptc/IptcBlock.java
src/main/java/org/apache/commons/imaging/formats/jpeg/iptc/IptcParser.java
src/test/java/org/apache/commons/imaging/formats/jpeg/iptc/IptcParserTest.java

Fixes two TODO's added some time ago when we had a 1.0 release vote. Simply makes `IptcBlock` members private and adds getters and setters.

[IMAGING-249]: Make IPTCBlock members private and add getter/setter

---

src/test/java/org/apache/commons/imaging/TestImageInfo.java

Reviewing this class I think there's a lot that needs changing. The `dump` method can probably be removed. The `toString()` could be simplified and also defensive against `null` values. But that's for another issue. For the moment, just adding tests.

Add tests for ImageInfo

---

src/changes/changes.xml

Used `git log` to locate changes, copied the description and issue ID from the merge commit.
Grouped multiple updates in a single change (i.e. if `dependency-a` was updated twice by the bot, we have only one entry, with two links to the PR's in GitHub).

Add changes.xml entries for dependabot (retroactively)

---

src/changes/changes.xml
src/main/java/org/apache/commons/imaging/formats/tiff/TiffImageParser.java
src/test/java/org/apache/commons/imaging/formats/tiff/TiffAlphaRoundTripTest.java

While this change addresses the special case of pre-multiplied alpha, there may be some system and JVM-version dependent issues.

IMAGING-312 Corrected handling of ExtraSamples tag

---

src/test/java/org/apache/commons/imaging/formats/png/PngWriteForceTrueColorText.java
src/test/java/org/apache/commons/imaging/roundtrip/PixelDensityRoundtrip.java

Fix two unit tests that were broken.
PixelDensityRoundtrip was now writing data in a byte array instead of a tmp file, but was trying to read the tmp file anyway.
And
PngWriteForceTrueColorText that was writing a png into a file named .gif, but was unable to read it because the extension was checked and refused by png parser.

Fix unit test

---

src/test/java/org/apache/commons/imaging/formats/jpeg/exif/ExifRewriterRoundtripTest.java

I believe I've uncovered a bug. Using the pattern shown in the `WriteExifMetadataExample` example code, it seems that some fields are not accurately copied. 
This unit test copies a test file to a temp file, and then compares the EXIF data of the two files. Each test inspects a different metadata class. Both tests fail, as there are minor differences found. 
[[IMAGING-351] EXIF data corruption during copy ](https://issues.apache.org/jira/browse/IMAGING-351)

[IMAGING-351] EXIF data corruption during copy

---

src/main/java/org/apache/commons/imaging/formats/png/PngImageParser.java
src/test/java/org/apache/commons/imaging/formats/png/PngImageParserTest.java

This PR makes sure the 'hasPalette' value is set correctly for PNG files.

[IMAGING-353] Fix PngImageParser hasPalette

---

src/test/java/org/apache/commons/imaging/formats/bmp/BmpImageParserTest.java
src/test/java/org/apache/commons/imaging/formats/bmp/BmpReadTest.java
src/test/java/org/apache/commons/imaging/formats/gif/GifReadTest.java
src/test/java/org/apache/commons/imaging/formats/icns/IcnsReadTest.java
src/test/java/org/apache/commons/imaging/formats/jpeg/JpegReadTest.java
src/test/java/org/apache/commons/imaging/formats/jpeg/JpegWithInvalidDhtSegmentTest.java
src/test/java/org/apache/commons/imaging/formats/jpeg/decoder/JpegDecoderTest.java
src/test/java/org/apache/commons/imaging/formats/jpeg/iptc/IptcParserTest.java
src/test/java/org/apache/commons/imaging/formats/jpeg/specific/JpegImageParserTest.java
src/test/java/org/apache/commons/imaging/formats/png/PngReadTest.java
src/test/java/org/apache/commons/imaging/formats/png/PngWithInvalidPngChunkSizeTest.java
src/test/java/org/apache/commons/imaging/formats/rgbe/RgbeReadTest.java
src/test/java/org/apache/commons/imaging/test/TestResources.java

Using `URL.getFile()` is faulty because its result is URL encoded. This caused test failures when running in a directory with spaces in its file path.

[IMAGING-359] Fix test resource file paths not being constructed properly

---

src/main/java/org/apache/commons/imaging/ImageInfo.java
src/main/java/org/apache/commons/imaging/formats/tiff/TiffImageParser.java
src/main/java/org/apache/commons/imaging/formats/tiff/constants/TiffConstants.java

This pull request adds more information about TIFF data compression variations to the ImageInfo available for TIFF files.
**Detail from Issue-360**
The ImageInfo for TIFF is missing information related to three TIFF compression options, two of which are quite commonly used. I propose to modify the TiffImageParser class to populate these values.
```
TIFF_COMPRESSION_DEFLATE_PKZIP 
TIFF_COMPRESSION_DEFLATE_ADOBE 
```
Additionally, the TIFF format has an obsolete variation on JPEG that was abandoned in the 1990's.  Commons Imaging does not currently support TIFF JPEG compression, though many of the pieces needed are already in its code base.  I propose to do the following:
The current code has a class called TiffConstants that includes the definition for
`    TIFF_COMPRESSION_JPEG = 6; ` …

Issue-360: Add more TIFF compression entries to ImageInfo

---

src/main/java/org/apache/commons/imaging/formats/tiff/TiffImageParser.java
src/test/java/org/apache/commons/imaging/formats/tiff/TiffReadImageInfoTest.java

This change addresses issues 337 and 361.  361 is redundant with 337.  The ImageInfo for TIFF was giving the wrong ColorType value for some TIFF files (it was hardwired to RGB).
I also made one unrelated cosmetic change on lines 619-626 where I fixed the indentation to match the Commons Imaging standard.
A new JUnit test for TIFF files was introduced to verify that expected values are obtained from ImageInfo, see TiffReadImageInfoTest.java

[IMAGING-337] Make ImageInfo state correct color type

---

src/main/java/org/apache/commons/imaging/formats/gif/GifImageParser.java
src/main/java/org/apache/commons/imaging/formats/gif/GifImagingParameters.java
src/test/java/org/apache/commons/imaging/formats/gif/GifReadTest.java

IMAGING-355 - Large animated GIF takes too much heap memory in getMetadata

[IMAGING-355] Large animated GIF takes too much heap memory in getMetadata

---

src/main/java/org/apache/commons/imaging/formats/tiff/TiffImageParser.java
src/test/java/org/apache/commons/imaging/formats/tiff/TiffReadTest.java

Avoid NullPointerException in TiffImageParser.getBufferedImage(TiffDirectory，ByteOrder,TiffImagingParameters) when TiffImagingParameters is null

Avoid NullPointerException in TiffImageParser.getBufferedImage()

---

src/main/java/org/apache/commons/imaging/formats/jpeg/xmp/JpegXmpRewriter.java

This removes the double `ImagingException` from the Javadoc and from the function throws

Remove double ImagingException
